# Generated by Django 4.1.2 on 2022-12-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0009_alter_course_ilo_alter_course_finals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='fname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='lname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='note1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='note1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='note2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='note2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='prep',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep', to=settings.AUTH_USER_MODEL),
        ),
    ]
