# Generated by Django 4.1.2 on 2022-12-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_alter_instructor_fname_alter_instructor_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='lname',
        ),
    ]
