# Generated by Django 4.1.2 on 2022-12-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0011_remove_instructor_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructor',
            name='lname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
