# Generated by Django 4.1.2 on 2022-12-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0012_instructor_instructor_instructor_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='lname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lname', to=settings.AUTH_USER_MODEL),
        ),
    ]
