# Generated by Django 4.1.2 on 2022-12-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0014_instructor_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='lname',
        ),
    ]
