# Generated by Django 4.1.3 on 2022-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0015_remove_instructor_fname_remove_instructor_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='co_req',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Co-requisites'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prerequisites'),
        ),
        migrations.AlterField(
            model_name='course',
            name='textbook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Textbooks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='textbook2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Supplemental Materials'),
        ),
    ]
