# Generated by Django 4.1.3 on 2022-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0016_alter_course_co_req_alter_course_prereq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='signatories',
        ),
        migrations.AddField(
            model_name='course',
            name='signatories',
            field=models.ManyToManyField(blank=True, null=True, to='syllabus.signature'),
        ),
    ]
